### ISSUE TITLE
Arguments "+" button does not work.

### ISSUE THREAD

**Issue by jmuheim** [ivanvc/mongodb-prefpane#3]
I'd like to store MongoDB's data not in the default folder /data/db, so I need to add an argument. But when clicking the "+" button in the preference pane, nothing happens.

**Comment by JeanMertz** [comment]
Same problem here. Possibly related to OS X Lion?

**Comment by jmuheim** [comment]
Wow, it's working now! No idea why. If it's still not working for you, I send you my org.ivanvc.mongo.plist file (by email) which you can modify for your own needs and copy it to /Users/josh/Library/Preferences/. Hope this helps.

**Comment by ivanvc** [comment]
Sorry for the late response, have been a little busy lately.

Can you either @sientia-jmu or @sientia-jmu give me more details about this problem? I have Lion too, and the latest version has been compiled against the latest Xcode version. If you can share the plist file, may be useful too.

Thanks!

**Comment by ivanvc** [comment]
Could it be that is failing just after the first launch? And then is working? I will try to reproduce it that way, and will fix it if that's it :wink:

**Comment by jmuheim** [comment]
I don't seem to be able to find the plist file anymore, haha. Can you tell me where it is stored?

**Comment by ivanvc** [comment]
It should be in `~/Library/Preferences/org.ivanvc.mongo.plist`. However I already find the way to reproduce it, and is just reproducible during the first run. So, am going to fix it.

Thanks for finding the bug! :+1:

**Comment by jmuheim** [comment]
Nice, thanks! :) I lost my arguments after upgrading the preference pane, though...
