### ISSUE TITLE
Feature request: automatically start on system startup

### ISSUE THREAD

**Issue by jmuheim** [ivanvc/mongodb-prefpane#4]
Something like MySQL's pref pane's auto startup feature would be nice:

https://skitch.com/jmuheim/esfgf/mysql

Thanks!

**Comment by ivanvc** [comment]
Hi @sientia-jmu, this is definitely something that I have planned, but never actually complete it. I will try to implement it soon.

**Comment by cliftonlabrum** [comment]
**Step 6** on this tutorial shows how to make MongoDB start on launch: http://manas.tungare.name/blog/how-to-install-mongodb-for-php-on-mac-os-x/

But just checking the box in this awesome PrefPane would be great. :) http://d.pr/i/hGEq

**Comment by ivanvc** [comment]
Hi @cliftonite, yes it shouldn't be that hard, and I'm planning on implementing this soon. However I've been packed with work to do, and unfortunately haven't been able to implement it. Hope to do it sooner rather than later :)
